# For more information, see https://aka.ms/devcontainer

# This is a base image for Python 3.9
FROM mcr.microsoft.com/devcontainers/python:3.9

# Install any additional OS packages you need here
# RUN apt-get update && apt-get install -y <package-name>

# Install Python packages
COPY requirements.txt /tmp/pip-tmp/
RUN pip install --no-cache-dir -r /tmp/pip-tmp/requirements.txt \
    && rm -rf /tmp/pip-tmp